default: &default
  adapter: postgresql
  encoding: unicode
  password:
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db_development

test:
  <<: *default
  database: db_development

production:
  <<: *default
  database: db_development
